version: '3.1'

services:
  visualizer:
    image: manomarks/visualizer
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

  updater:
    image: 7imbrook/auto-service-updater
    ports:
      - 30000:3000
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
