version: '3.1'

services:
  web:
    image: ritsse/onerepo
    ports:
      - 80:80
      - 443:443
    environment:
      - 'SITE_ROOT=https://ssedev.se.rit.edu'
      - 'API_UPSTREAM=https://sse.rit.edu/'
    volumes:
      - caddycache:/root/.caddy

volumes:
  caddycache:
