version: 2

jobs:
  build:
    docker:
      - image: docker:17.03.0-ce
    working_directory: ~/OneRepo
    steps:
      - setup_remote_docker
      - run:
          name: Show Info
          command: |
            docker version
            docker info
      - checkout
      - run:
          name: Build the current image
          command: |
            TAG=dev2.0.$CIRCLE_BUILD_NUM
            docker build -f Dockerfile -t ritsse/onerepo:$TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push ritsse/onerepo:$TAG
