version: 2

jobs:
  build:
    docker:
      - image: docker:17.03.0-ce
    working_directory: ~/OneRepo
    steps:
      - setup_remote_docker
      - run:
          name: Show Info
          command: |
            docker version
            docker info
      - checkout
      - run:
          name: Build the current image
          command: |
            docker build -f Dockerfile .
